name: Build Frameworks
permissions:
    contents: read
    statuses: read
    pull-requests: read
    actions: read
    checks: write
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    build:
        name: Build Framework (${{ matrix.configuration['platform'] }})
        runs-on: macos-12
        strategy:
            fail-fast: false
            matrix:
                configuration:
                    -   scheme: LDKFramework
                        destination: generic/platform=iOS
                        platform: iOS
                        project: LDK/LDKFramework.xcodeproj
                        workspace: LDKFramework.xcworkspace
                    -   scheme: LDKFramework
                        destination: platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro
                        platform: iOS Simulator
                        project: LDK/LDKFramework.xcodeproj
                    -   scheme: LDKFramework_Mac
                        destination: generic/platform=OS X
                        platform: OS X
                        project: LDK/LDKFramework.xcodeproj
                    -   scheme: LDKFramework
                        destination: platform=macOS,variant=Mac Catalyst,arch=x86_64
                        platform: Mac Catalyst
                        project: LDK/LDKFramework.xcodeproj
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
            LDK_C_BINDINGS_BASE: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/ldk-c-bindings
            LDK_C_BINDINGS_BINARY_DIRECTORY: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/bin
        steps:
            -   name: Configure Xcode
                uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                uses: ./.github/actions/install-dependencies
            -   name: Build
                id: build
                uses: ./.github/actions/build-for-testing
                with:
                    project: ${{ matrix.configuration['project'] }}
                    scheme: ${{ matrix.configuration['scheme'] }}
                    destination: ${{ matrix.configuration['destination'] }}
