name: Build Frameworks
permissions:
  contents: read
  statuses: read
  pull-requests: read
  actions: read
  checks: write
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"

jobs:
  build:
    name: Build Framework (${{ matrix.configuration['platform'] }})
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - scheme: LDKFramework
          destination: generic/platform=iOS
          platform: iOS
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro
          platform: iOS Simulator
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework_Mac
          destination: generic/platform=OS X
          platform: OS X
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=macOS,variant=Mac Catalyst,arch=x86_64
          platform: Mac Catalyst (x86_64)
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=macOS,variant=Mac Catalyst,arch=arm64
          platform: Mac Catalyst (arm64)
          workspace: LDKFramework.xcworkspace
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
    - name: Configure Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies
    - name: Build
      id: build
      uses: ./.github/actions/build-for-testing
      with:
        workspace: ${{ matrix.configuration['workspace'] }}
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
