name: Release Framework
permissions:
  contents: read
  statuses: read
  pull-requests: read
  actions: read
  checks: write
on:
  push:
    tags:
      - "*"

jobs:
  archive:
    name: Archive Frameworks (${{ matrix.configuration['platform'] }})
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - scheme: LDKFramework
          destination: generic/platform=iOS
          platform: iOS
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro
          platform: iOS Simulator
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework_Mac
          destination: generic/platform=OS X
          platform: Darwin
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=macOS,variant=Mac Catalyst,arch=x86_64
          platform: Catalyst
          workspace: LDKFramework.xcworkspace
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
      BUILD_DIR: ./build
    steps:
    - name: Configure Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies
    - name: Archive
      uses: ./.github/actions/archive-framework
      with:
        workspace: ${{ matrix.configuration['workspace'] }}
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
        platform: ${{ matrix.configuration['platform'] }}
    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: LDKFramework-${{ matrix.configuration['platform'] }}.xcarchive
        path: |
          ./xcode/build/LDKFramework-${{ matrix.configuration['platform'] }}.xcarchive
  create-xcframework:
    name: Create Fat Framework
    runs-on: macos-12
    needs: [archive]
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
      BUILD_DIR: ./build
    steps:
      - name: Download xcarchives
        uses: actions/download-artifact@v3
      - name: Create xcframework and release
        run: |
          xcodebuild -create-xcframework \
            -framework LDKFramework-iOS.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
            -framework LDKFramework-iOS\ Simulator.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
            -framework LDKFramework-Catalyst.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
            -framework LDKFramework-Darwin.xcarchive/Products/Library/Frameworks/LDKFramework_Mac.framework \
            -output LDKFramework.xcframework
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LDKFramework-iOS.xcarchive
            LDKFramework-iOS\ Simulator.xcarchive
            LDKFramework-OS\ X.xcarchive
            LDKFramework-Mac\ Catalyst.xcarchive
            LDKFramework.xcframework
