name: Release Framework
permissions:
  contents: read
  statuses: read
  pull-requests: read
  actions: read
  checks: write
on:
  push:
    tags:
      - '*'

env:
  BUILD_DIR: ./build

jobs:
  archive:
    name: Archive Frameworks (${{ matrix.configuration['platform'] }})
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - scheme: LDKFramework
          destination: generic/platform=iOS
          platform: iOS
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro
          platform: iOS Simulator
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework_Mac
          destination: generic/platform=OS X
          platform: OS X
          workspace: LDKFramework.xcworkspace
        - scheme: LDKFramework
          destination: platform=macOS,variant=Mac Catalyst,arch=x86_64
          platform: Mac Catalyst
          workspace: LDKFramework.xcworkspace
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
    - name: Configure Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies
    - name: Archive
      uses: ./.github/actions/archive-framework
      with:
        workspace: ${{ matrix.configuration['workspace'] }}
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
        platform: ${{ matrix.configuration['platform'] }}
  create-xcframework:
    name: Create xcframework
    runs-on: macos-12
    needs: [archive]
    run: |
      xcodebuild -create-xcframework \
        -framework ${BUILD_DIR}/LDKFramework-iOS.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
        -framework ${BUILD_DIR}/LDKFramework-iOS\ Simulator.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
        -framework ${BUILD_DIR}/LDKFramework-OS\ X.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
        -framework ${BUILD_DIR}/LDKFramework-Mac\ Catalyst.xcarchive/Products/Library/Frameworks/LDKFramework.framework \
        -output ${BUILD_DIR}/LDKFramework.xcframework
  - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${BUILD_DIR}/LDKFramework.xcframework
